# Generated by Django 5.2.6 on 2025-09-09 19:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_teacher_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_created', to='lessons.teacher'),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='is_swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonrecord',
            name='swapped_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_swapped', to='lessons.teacher'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='status',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not Attended', 'Not Attended'), ('Pending', 'Pending'), ('Swap Pending', 'Swap Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Not Attended', max_length=20),
        ),
    ]
