# Generated by Django 5.2.6 on 2025-09-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessonrecord_created_at_lessonrecord_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to='lessons.teacher'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended'), ('Not Attended', 'Not Attended'), ('Swap Pending', 'Swap Pending'), ('Swap Approved', 'Swap Approved'), ('Swap Rejected', 'Swap Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='swapped_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swapped_lessons', to='lessons.teacher'),
        ),
    ]
