# Generated by Django 5.2.6 on 2025-09-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessonrecord_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonrecord',
            unique_together={('timetable', 'week')},
        ),
    ]
