# Generated by Django 5.2.6 on 2025-09-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessonrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_lessons', to='lessons.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended'), ('Not Attended', 'Not Attended')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_records', to='lessons.timetable'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_records', to='lessons.week'),
        ),
        migrations.RemoveField(
            model_name='lessonrecord',
            name='is_swap',
        ),
        migrations.RemoveField(
            model_name='lessonrecord',
            name='swapped_with',
        ),
    ]
