# Generated by Django 5.2.6 on 2025-09-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lessonrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessonrecord',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.timetable'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.week'),
        ),
    ]
