# Generated by Django 5.2.6 on 2025-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_timetable_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
