# Generated by Django 5.2.6 on 2025-09-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_timetable_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.subject'),
        ),
    ]
