# Generated by Django 5.2.6 on 2025-09-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_remove_timetable_subject_timetable_subject_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
    ]
